<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BwfTagcloud\Module'                                 => __DIR__ . '/Module.php',
    'BwfTagcloud\Model\DataProvider'                     => __DIR__ . '/src/BwfTagcloud/Model/DataProvider.php',
    'BwfTagcloud\Model\Table\BwfTagcloudAggregateEntity' => __DIR__ . '/src/BwfTagcloud/Model/Table/BwfTagcloudAggregateEntity.php',
    'BwfTagcloud\Model\Table\BwfTagcloudEntity'          => __DIR__ . '/src/BwfTagcloud/Model/Table/BwfTagcloudEntity.php',
    'BwfTagcloud\View\AppendResources'                   => __DIR__ . '/src/BwfTagcloud/View/AppendResources.php',
    'BwfTagcloud\View\Renderer'                          => __DIR__ . '/src/BwfTagcloud/View/Renderer.php',
);